/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:1f7cfdbc-18ab-4b8f-88c4-d0d59d7576f1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_WIvexnanI",
    "aws_user_pools_web_client_id": "2499th6h5227pndphgbq6no2p8",
    "oauth": {}
};


export default awsmobile;
